volumes:
  db: {}

services:
  mysql:
    image: mysql
    environment:
      MYSQL_DATABASE: db
      MYSQL_USER: springuser
      MYSQL_PASSWORD: ThePassword
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
    ports:
      - 8083:3306
    volumes:
      - db:/var/lib/mysql

